# Generated by Django 6.1 on 2026-09-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('tickets_created', models.PositiveIntegerField(default=0)),
                ('tickets_updated', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('startup', 'Startup')], default='manual', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(help_text='ServiceDesk Plus request ID.', max_length=100, unique=True)),
                ('system_name', models.CharField(help_text='Request subject.', max_length=500)),
                ('technician', models.CharField(blank=True, max_length=255)),
                ('responsible_person', models.CharField(blank=True, help_text='Requester name.', max_length=255)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(help_text='Raw status.name from ServiceDesk Plus.', max_length=100)),
                ('status_color', models.CharField(blank=True, help_text='Raw status.color from ServiceDesk Plus.', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, help_text='ServiceDesk Plus created_time.', null=True)),
                ('sla_due_at', models.DateTimeField(blank=True, help_text='ServiceDesk Plus due_by_time.', null=True)),
                ('is_overdue', models.BooleanField(default=False, help_text='ServiceDesk Plus is_overdue flag, refreshed each sync.')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_days', models.IntegerField(blank=True, null=True)),
                ('sla_met', models.BooleanField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_synced_at'],
            },
        ),
    ]
