# Generated by Django 6.1 on 2026-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickectTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_policy_name',
            field=models.CharField(blank=True, help_text='Applied SLA policy name.', max_length=255),
        ),
    ]
