# Generated by Django 6.1 on 2026-09-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickectTracker', '0002_ticket_sla_policy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approval_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
