# Generated by Django 6.1 on 2026-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickectTracker', '0003_ticket_approval_status_ticket_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approval_team',
            field=models.CharField(blank=True, help_text='udf_sline_13201 — meaning inferred.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='approver_1',
            field=models.CharField(blank=True, help_text='udf_sline_2401.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='approver_2',
            field=models.CharField(blank=True, help_text='udf_sline_2402.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='detail_synced',
            field=models.BooleanField(default=False),
        ),
    ]
