# Generated by Django 6.1 on 2026-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickectTracker', '0004_ticket_approval_team_ticket_approver_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='ServiceDesk Plus assigned_time — the SLA clock start.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='template_id',
            field=models.CharField(blank=True, help_text='Used to look up the SLA day-window.', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_overdue',
            field=models.BooleanField(default=False, help_text="Computed from assigned_at + the template's SLA window, refreshed each sync."),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, help_text='ServiceDesk Plus due_by_time — display only, not used for compliance.', null=True),
        ),
    ]
